site_name: GraphDJ
site_url : https://hlop3z.github.io/graphdj
repo_url: https://github.com/hlop3z/graphdj
copyright: Copyright © Hlop3z

theme:
  name: material
  locale: en
  features:
    - navigation.tabs  
  icon:
    logo: material/cards-playing-outline
  palette:
    primary: light blue


markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.tabbed

nav:
    - Getting Started:
      - Introduction: index.md
      - Setup   : configure/setup.md
      - Settings: configure/settings.md
      - Users   : configure/users.md
      - Models  : configure/models.md
      - URLs / Schema : configure/urls.md

    - Tutorial:
      - Install: tutorial/install.md
      - Create App: tutorial/create-app.md

    - Cheat Sheet:
      - Commands: commands.md
      - Pipenv: pipenv.md
      - Client: client.md

plugins:
  #- mike
  - search:
      separator: '[\s\-\.]+'

extra:
  version: 1.0